### ISSUE TITLE
Setup Histogram Plot with Scatter Plot

### ISSUE THREAD

**Issue by swamilikes2code** [swamilikes2code/Python_based_Interactive_Scientific_Visualization#35]

**Comment by too223** [comment]
Commits associated: 080d0c815615057dbaaab4dc3de689102ae104a0 5065f4580ccc6137d7ce126868287361ec0d0cc5 2cdc28e39aded9f20823fbf1862998d40cdf0c12 3a849b4c2b3097b359a6f0268dac96c683255b90 a8714d0e6453339b8c438237302e63ed1c44a84a 55291c49fe89e30f477fa3ba2f585e80e395bff6 35ac51b1ec8bfb32d7f32bb404e1480a3a28e98b
